version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "prettier"
          - "eslint-config-*"
          - "eslint-plugin-*"
          - "typescript-eslint"
