name: dependabot automerge

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  lint:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/dependabot-automerge.yml@2f12e0eb5d446e4f36a1247417445beda6ac474e # v0.4.1
